name: kasiemonitor
description: Monitor App for Kasie Backend
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  kasie_transie_library:
    path: ../kasie_transie_library
  cupertino_icons: ^1.0.5
  flutter_local_notifications: ^15.1.0+1
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  focused_menu: ^1.0.5
  #  intl: ^0.18.0
  firebase_dynamic_links: ^5.3.4
  timezone: ^0.9.2
  json_annotation: ^4.8.1
  dio: ^5.3.3
  get_it: ^7.6.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/l10n/
    - assets/
    - assets/projects/
    - assets/payment/
    - assets/markers/
    - assets/numbers/
    - .env
